import { Card, Set } from '@/lib/database.types';

// We import the official data generated by scripts/fetch-cards.js
// If for some reason this file doesn't exist, we fall back to an empty array to avoid crash, 
// but in this environment it SHOULD exist.
import OFFICIAL_DATA from '@/data/official-cards.json';

export const MOCK_SETS: Set[] = [
    { id: 'set1', name: 'Origins', code: 'ORI', release_date: '2024-01-01', total_cards: 318 },
    { id: 'set2', name: 'Rising Tides', code: 'RIT', release_date: '2024-04-01', total_cards: 122 },
    { id: 'set3', name: 'Mountain Call', code: 'COT', release_date: '2024-07-01', total_cards: 189 },
    { id: 'set4', name: 'Empires', code: 'EMP', release_date: '2024-10-01', total_cards: 218 },
];

// Cast the JSON data to our Card type
// We ensure compatibility during the fetch script mapping
export const MOCK_CARDS: Card[] = OFFICIAL_DATA as unknown as Card[];

export async function getCards(query?: string): Promise<Card[]> {
    // Simulate network delay for realism
    await new Promise(resolve => setTimeout(resolve, 300));

    if (!query) return MOCK_CARDS;

    const lowerQuery = query.toLowerCase();
    return MOCK_CARDS.filter(card =>
        card.name.toLowerCase().includes(lowerQuery) ||
        (card.text && card.text.toLowerCase().includes(lowerQuery)) ||
        card.type.toLowerCase().includes(lowerQuery)
    );
}

export async function getCardById(id: string): Promise<Card | undefined> {
    await new Promise(resolve => setTimeout(resolve, 100));
    return MOCK_CARDS.find(c => c.id === id);
}
