import { Card } from '@/lib/database.types';
import OFFICIAL_CARDS_RAW from '@/data/official-cards.json';

const ALL_CARDS = OFFICIAL_CARDS_RAW as unknown as Card[];

export interface StarterDeck {
    id: string;
    name: string;
    description: string;
    regions: string[];
    mainChampions: string[];
    cards: { name: string; count: number }[];
}

export const STARTER_DECKS: StarterDeck[] = [
    {
        id: 'deck-arcane-collection',
        name: 'Arcane Box Set',
        description: 'Featuring the stars of the hit series Arcane.',
        regions: ['Piltover & Zaun'],
        mainChampions: ['Jinx', 'Vi', 'Caitlyn', 'Ekko', 'Viktor', 'Heimerdinger', 'Warwick'],
        cards: [
            { name: 'Jinx', count: 3 },
            { name: 'Vi', count: 3 },
            { name: 'Caitlyn', count: 3 },
            { name: 'Ekko', count: 3 }, // Added for flavor if specific card exists
            { name: 'Viktor', count: 3 },
            { name: 'Heimerdinger', count: 3 },
            { name: 'Warwick', count: 3 }, // Often specific to Arcane
            { name: 'Get Excited!', count: 3 },
            { name: 'Mystic Shot', count: 3 },
            { name: 'Flashbomb Trap', count: 3 },
            { name: 'Hexcore Foundry', count: 2 },
            { name: 'Thermogenic Beam', count: 3 },
            { name: 'Gotcha!', count: 2 },
            { name: 'Officer Squad', count: 2 },
            { name: 'Ambush', count: 1 } // Flavor
        ]
    },
    {
        id: 'deck-proving-grounds-demacia',
        name: 'Proving Grounds: Might',
        description: 'The might of Demacia, led by Garen and Lux.',
        regions: ['Demacia'],
        mainChampions: ['Garen', 'Lux'],
        cards: [
            { name: 'Garen', count: 3 },
            { name: 'Lux', count: 3 },
            { name: 'Vanguard Defender', count: 3 },
            { name: 'Cithria of Cloudfield', count: 3 },
            { name: 'Purify', count: 2 },
            { name: 'Single Combat', count: 3 },
            { name: 'Judgement', count: 1 },
            { name: 'Final Spark', count: 3 }, // Generated by Lux usually, but included if maindeck
            { name: 'Remembrance', count: 2 },
            { name: 'Radiant Guardian', count: 3 },
            { name: 'Tianna Crownguard', count: 2 },
            { name: 'Unyielding Spirit', count: 1 },
            { name: 'Concerted Strike', count: 3 },
            { name: 'Sharpsight', count: 3 }
        ]
    },
    {
        id: 'deck-proving-grounds-mystic',
        name: 'Proving Grounds: Flow',
        description: 'Master Yi and the Ionian technique.',
        regions: ['Ionia'],
        mainChampions: ['Master Yi', 'Karma'],
        cards: [
            { name: 'Master Yi', count: 3 },
            { name: 'Karma', count: 3 },
            { name: 'Deny', count: 3 },
            { name: 'Twin Disciplines', count: 3 },
            { name: 'Rivershaper', count: 3 },
            { name: 'Eye of the Dragon', count: 3 },
            { name: 'Deep Meditation', count: 3 },
            { name: 'Concussive Palm', count: 3 },
            { name: 'Will of Ionia', count: 2 },
            { name: 'Spirit\'s Refuge', count: 2 },
            { name: 'Wuju Style', count: 3 },
            { name: 'Meditate', count: 2 },
            { name: 'Scales of the Dragon', count: 3 },
            { name: 'Dragonling', count: 3 } // Token, but representing presence
        ]
    },
    {
        id: 'deck-origins-starter',
        name: 'Origins: First Flame',
        description: 'The fire of Annie burns bright in this starter deck.',
        regions: ['Noxus'],
        mainChampions: ['Annie', 'Darius'],
        cards: [
            { name: 'Annie', count: 3 },
            { name: 'Darius', count: 2 },
            { name: 'Legion Rearguard', count: 3 },
            { name: 'Disintegrate', count: 3 },
            { name: 'Ravenbloom Conservatory', count: 2 },
            { name: 'Tibbers', count: 1 }, // Token usually
            { name: 'Noxian Fervor', count: 3 },
            { name: 'Decimate', count: 2 },
            { name: 'Captive Greyback', count: 3 },
            { name: 'Spell Slinger', count: 3 },
            { name: 'House Spider', count: 3 },
            { name: 'Arachnoid Horror', count: 3 },
            { name: 'Pirouette', count: 3 },
            { name: 'Legion Saboteur', count: 3 }
        ]
    }
];


// Helper to hydrate decks
export const getHydratedStarterDecks = (): any[] => {
    return STARTER_DECKS.map(deck => {
        const hydratedCards: any[] = [];
        deck.cards.forEach(item => {
            const cardData = ALL_CARDS.find(c => c.name.toLowerCase() === item.name.toLowerCase());
            if (cardData) {
                // Determine foil/normal based on count? Nah, just normal
                hydratedCards.push({
                    card: cardData,
                    count: item.count
                });
            }
        });

        return {
            ...deck,
            coverImage: hydratedCards[0]?.card.image_url,
            totalCards: hydratedCards.reduce((acc, c) => acc + c.count, 0),
            items: hydratedCards
        };
    });
};
